insert into city (id, name) values (1, 'Beograd');
insert into city (id, name) values (2, 'Nis');
insert into city (id, name) values (3, 'Novi Sad');

insert into app_user (id, email, username, password, first_name, last_name, roles) values (1, 'admin@test.com', 'admin', 'admin', 'Admin', 'Admin', 'ROLE_ADMIN');
insert into app_user (id, email, username, password, first_name, last_name, roles) values (2, 'manager@test.com', 'manager', 'manager', 'Manager', 'Manager', 'ROLE_MANAGER');
insert into app_user (id, email, username, password, first_name, last_name, roles) values (3, 'user@test.com', 'user', 'user', 'User', 'User', 'ROLE_USER');
insert into app_user (id, email, username, password, first_name, last_name, roles) values (4, 'bojan@test.com', 'bojan', 'test12', 'Bojan', 'Ilic', 'ROLE_USER');
insert into app_user (id, email, username, password, first_name, last_name, roles) values (5, 'jelena@test.com', 'jelena', 'test12', 'Jelena', 'Lukovic', 'ROLE_USER');

insert into cinema (id, name, address, phone_number, image, city_id) values (1, 'VikingR Beograd', 'Ustanicka 107', '0651234567', '/uploads/images/cinema3.jpeg', 1);
insert into cinema (id, name, address, phone_number, image, city_id) values (2, 'VikingR Nis', 'Makedonska 52', '0667894512', '/uploads/images/cinema1.jpg', 2);
insert into cinema (id, name, address, phone_number, image, city_id) values (3, 'VikingR Novi Sad', 'Bulevar Kralja Aleksandra 55', '0634561239', '/uploads/images/cinema5.jpg', 3);

insert into movie (id, title, duration, year, rating, director, writer, stars, image, trailer_URL, genre, country, is_showing, description)
    values (1, '12 Angry Men', 96, 1957, 8.9, 'Sidney Lumet', 'Reginald Rose', 'Henry Fonda, Lee J. Cobb, Martin Balsam', '/uploads/images/12-angry-men.jpg', 'https://www.youtube.com/embed/_13J_9B5jEk', 'Crime, Drama', 'USA', true, 'The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors'' prejudices and preconceptions about the trial, the accused, and each other. Based on the play, all of the action takes place on the stage of the jury room.');
insert into movie (id, title, duration, year, rating, director, writer, stars, image, trailer_URL, genre, country, is_showing, description)
    values (2, 'Se7en', 127, 1995, 8.6, 'David Fincher', 'Andrew Kevin Walker', 'Morgan Freeman, Brad Pitt, Kevin Spacey', '/uploads/images/seven.jpg', 'https://www.youtube.com/embed/znmZoVkCjpI', 'Crime, Drama, Mystery', 'USA', true, 'A film about two homicide detectives'' (Morgan Freeman and Brad Pitt) desperate hunt for a serial killer who justifies his crimes as absolution for the world''s ignorance of the Seven Deadly Sins. The movie takes us from the tortured remains of one victim to the next as the sociopathic "John Doe" (Kevin Spacey) sermonizes to Detectives Somerset and Mills -- one sin at a time. The sin of Gluttony comes first and the murderer''s terrible capacity is graphically demonstrated in the dark and subdued tones characteristic of film noir. The seasoned and cultured but jaded Somerset researches the Seven Deadly Sins in an effort to understand the killer''s modus operandi while the bright but green and impulsive Detective Mills (Pitt) scoffs at his efforts to get inside the mind of a killer...');
insert into movie (id, title, duration, year, rating, director, writer, stars, image, trailer_URL, genre, country, is_showing, description)
    values (3, 'Pulp Fiction', 154, 1994, 8.9, 'Quentin Tarantino', 'Quentin Tarantino', 'John Travolta, Uma Thurman, Samuel L. Jackson', '/uploads/images/pulp-fiction.jpg', 'https://www.youtube.com/embed/s7EdQ4FqbhY', 'Crime, Drama', 'USA', true, 'Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.');
insert into movie (id, title, duration, year, rating, director, writer, stars, image, trailer_URL, genre, country, is_showing, description)
    values (4, 'The Godfather', 175, 1972, 9.2, 'Francis Ford Coppola', 'Mario Puzzo', 'Marlon Brando, Al Pacino, James Caan', '/uploads/images/the-godfather.jpg', 'https://www.youtube.com/embed/sY1S34973zA', 'Crime, Drama', 'USA', true, 'The Godfather "Don" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter''s wedding. Michael, Vito''s youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Don''s influence for the same, Vito refuses to do it. What follows is a clash between Vito''s fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart.');
insert into movie (id, title, duration, year, rating, director, writer, stars, image, trailer_URL, genre, country, is_showing, description)
    values (5, 'Shawshank Redemption', 142, 1994, 9.3, 'Frank Darabont', 'Stephen King, Frank Darabont', 'Tim Robbings, Morgan Freeman, Bob Gunton', '/uploads/images/shawshank-redemption.jpg', 'https://www.youtube.com/embed/6hB3S9bIaco', 'Drama', 'USA', true, 'Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man''s unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.');
insert into movie (id, title, duration, year, rating, director, writer, stars, image, trailer_URL, genre, country, is_showing, description)
    values (6, 'Fight Club', 139, 1999, 8.8, 'David Fincher', 'Chuck Palahniuk, Jim Uhls', 'Brad Pitt, Edward Norton, Meat Loaf', '/uploads/images/fight-club.jpg', 'https://www.youtube.com/embed/SUXWAEX2jlg', 'Drama', 'USA', true, 'A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power. When the narrator is exposed to the hidden agenda of Tyler''s fight club, he must accept the awful truth that Tyler may not be who he says he is.');

insert into showing_type (id, name) values (1, '4K');
insert into showing_type (id, name) values (2, '4K 3D');
insert into showing_type (id, name) values (3, 'Digital 2D');
insert into showing_type (id, name) values (4, 'Digital 3D');
insert into showing_type (id, name) values (5, 'MX4D 2D');
insert into showing_type (id, name) values (6, 'MX4D 3D');

insert into club (id, name, price, image, description) values (1, 'CineStar Premium Membership', 5000, '/uploads/images/premium.png', 'Become premium member by paying 5000 RSD yearly. Benefits: 10% discount on ticket prices. Pick up reserved tickets up to 10 minutes before the start of the screening (instead of the usual 30 minutes). An exclusive tour of the CineStar cinema. Invitation for premieres and special events.');
insert into club (id, name, price, image, description) values (3, 'CineStar Standard Membership' , 2000, '/uploads/images/standard.png', 'Become standard member by paying 2000 RSD yearly. Benefits: Pick up reserved tickets up to 10 minutes before the start of the screening (instead of the usual 30 minutes). Free parking. Invitation for premieres and special events.');
insert into club (id, name, price, image, description) values (2, 'CineStar Premium Bonus Card ', 1000, '/uploads/images/premium-card.png', 'Buy CineStar bonus card and use card for the rest of your life. Benefits: 1 bonus point for every RSD spent. Attractive prizes in exchange for point. Buy tickets with earned bonus points. Online check of points status.');
